### ISSUE TITLE
Question about regression

### ISSUE THREAD

**Issue by pavlin-policar** [jwittenbach/polyseq#7]
Hi, thanks for the interesting package. I've looked over the code and have found the regression module to be quite useful. However, I do have a question and I'm pasting your code here to make things easier.

```
def regress(data, regressors, n_processes=1):
    model = LinearRegression(n_jobs=n_processes)
    model.fit(regressors, data)

    y_hat = model.predict(regressors)
    residuals = data - y_hat

    zscores = (residuals - residuals.mean())/residuals.std()
    return ExpressionMatrix(zscores, columns=data.columns)
```

I'm curious why you do ` (residuals - residuals.mean())/residuals.std()` instead of ` (residuals - residuals.mean(axis=0))/residuals.std(axis=0)`. Each gene has a separate set of weights associated with the regression, and the genes are treated independently. So I don't understand why you're pooling the mean and std over all genes here.

**Comment by jwittenbach** [comment]
Hey @pavlin-policar -- I think you're right and this must be a mistake. I'm testing it now and putting together a PR to fix it. Thanks for catching this!

**Comment by jwittenbach** [comment]
@pavlin-policar: OK, after looking into this, I think the code is actually OK and is already doing what you would want it to.

The key is that `data` is an `ExpressionMatrix` -- which is just a simple subclass of a pandas `DataFrame` -- and not a NumPy `ndarray`. If it were an `ndarray`, then you are correct that the default is to reduce over all dimensions and so specifying `axis=0` is necessary. However, for a `DataFrame`, the default  behavior is to only reduce over the rows, so the behavior is actually correct even without specifying `axis=0`.

Simple test:
```
np.array_equal(residuals.mean(axis=0).__array__(), residuals.mean().__array__())
```
returns `True`

**Comment by pavlin-policar** [comment]
Oh, I see, sorry for the confusion. I'm so used to dealing with numpy arrays that I didn't realise the default behaviour for pandas was different. Thanks!
